### ISSUE TITLE
Block hardness

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/Midnight#9] opened 2018-10-18 01:48 UTC
midnight furnaces, dark pearl blocks, and midnight dirt have no hardness value assigned to them, and if you accidentally break your dark pearl block or midnight furnace WITHOUT your pickaxe, they gone

**Comment by gegy1000** [comment] 2018-10-18 04:52
Duplicate of #6

**Closed by gegy1000** 2018-10-18 04:52 UTC
